BPTL Dashboard: Add homecollection APIs (Part 2.3)
episphere/connectFaas pull request #466
Opened 2023-11-17 17:15 UTC by abhinavjonnada82

https://github.com/episphere/connect/issues/771
Related PR:
https://github.com/episphere/biospecimen/pull/622

Updated APIs to enhance functionality & fix errors

2023-11-17 19:33 UTC, ramavavi approved these changes

2023-11-17 19:34 UTC, ramavavi commented
looks good.

2023-11-17 19:39 UTC, Gbarra9 approved these changes
Looks good. (concept id for BioKit_Mouthwash updated)

2023-11-17 20:06 UTC, we-ai commented on utils/firestore.js
>                              '221592017': '849527480'
849527480 as number.

2023-11-17 20:07 UTC, we-ai commented on utils/firestore.js
> +        const snapshot = await db.collection("participants").where('173836415.266600170.8583443674.221592017', '==', '849527480').get();
849527480 as number

2023-11-17 20:07 UTC, we-ai commented on utils/firestore.js
>                          '221592017': '241974920',
390351864 and 241974920 as numbers

2023-11-17 20:08 UTC, we-ai commented on utils/firestore.js
>                          '221592017': '277438316',
277438316 as number

2023-11-17 20:08 UTC, we-ai commented on utils/firestore.js
>                  '221592017': '375535639',
number

2023-11-17 20:10 UTC, we-ai requested changes
Make sure concept IDs are numbers when used as values, otherwise downstream logics may/will break.

2023-11-17 20:37 UTC, we-ai approved these changes
Looks good.

2023-11-17 21:01 UTC, jhflorey approved these changes
look good

2023-11-18 04:01 UTC, jhflorey approved these changes

2023-11-20 15:42 UTC, merged